# Generated by Django 4.2.7 on 2023-12-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_clientes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
